version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - echo "Building the project..."
      - echo "Hello World"
      - echo "<html><body><h1>Welcome to My Project</h1></body></html>" > index.html

artifacts:
  files:
    - index.html
